### ISSUE TITLE
Rebase/merge upstream master (https://github.com/buildroot/buildroot)?

### ISSUE THREAD

**Issue by craigcarnell** [openlgtv/buildroot-nc4#11]
buildroot has lots of nice stuff like GCC 12.2.0 as well as numerous other changes.

**Comment by smx-smx** [comment]
gcc 12 is already available as a prerelease. I can merge other changes this weekend

**Comment by craigcarnell** [comment]
@smx-smx Looking forward to it :+1:

**Comment by smx-smx** [comment]
Done: https://github.com/openlgtv/buildroot-nc4/releases/tag/webos-f489baf
Please check and close the issue if it's all good

**Comment by craigcarnell** [comment]
@smx-smx Great work!! Downloading now and re-compiling :+1: Will let you know if it doesn't work

**Comment by craigcarnell** [comment]
@smx-smx works great thanks
