### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by IngwiePhoenix** [openlgtv/buildroot-nc4#44]
Hello!

I am trying to set up automated builds for this on aarch64/arm64 on a RockChip RK3588.

To do so, I would like to know:

1. How do I build the tool with 0 user input by having it automatically read the correct config? I suppose it's probably just setting a environment variable, but I couldn't figure out which one.
2. Produced archives can be moved to `$ARCHIVE/`. Is there a dedicated `make dist` command or alike that generates the archive for me, and if so, how do I tell it where to put it? Alternatively, what is it's default location relative to the source root so I can just move it there myself?

Here is an example: https://github.com/IngwiePhoenix/laminar-ci-scripts/blob/master/cfg/jobs/webos-sdk.run

Thanks and kind regards,
Ingwie

**Comment by smx-smx** [comment]
You can consult the CI runner script, which should answer all your questions:
https://github.com/openlgtv/buildroot-nc4/blob/master/.cirrus.yml

**Comment by IngwiePhoenix** [comment]
Thanks, that did help!
Now I can work on fiding out the issues and stuff... but not today ^^'
https://builds.birb.it/jobs/webos-sdk-nc4/3
