### ISSUE TITLE
clock_gettime not defined?

### ISSUE THREAD

**Issue by IngwiePhoenix** [openlgtv/buildroot-nc4#5]
I was trying to build Kodi's dependencies by using their setup (`kodi/tools/depend`). And a whole lot passes surprisingly easily! However, when the build comes to `libinput`, it fails:

```
/timeit.py
ingwie@bigboi:/opt/xbmc/tools/depends/target/libinput/arm-webos-linux-gnueabi-release/build$ /opt/arm-webos-linux-gnueabi_sdk-buildroot/usr/bin/arm-webos-linux-gnueabi-gcc  -o libinput-model-quirks libinput-model-quirks.p/udev_libinput-model-quirks.c.o -L/opt/kodi-deps/arm-webos-linux-gnueabi-release/lib -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath-link=/opt/kodi-deps/arm-webos-linux-gnueabi-release/lib -Wl,--start-group /opt/kodi-deps/arm-webos-linux-gnueabi-release/lib/libudev.a -Wl,--end-group
/opt/arm-webos-linux-gnueabi_sdk-buildroot/bin/../lib/gcc/arm-webos-linux-gnueabi/11.2.0/../../../../arm-webos-linux-gnueabi/bin/ld: /opt/kodi-deps/arm-webos-linux-gnueabi-release/lib/libudev.a(time-util.o): in function `now':
time-util.c:(.text+0x84): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
```

I've tried my best to see which dynamic library defines this function as it is referenced in `unistd.h` and thus should be either defined in glibc or libc; but no luck.

Any other idea what I could do here to fix this? Thanks!

**Comment by smx-smx** [comment]
Try adding -lrt

Newer glibc versions no longer use/require it (and therefore packages sometimes forget about this) but i'm using an older one for backward compatibility

**Comment by craigcarnell** [comment]
@IngwiePhoenix How did you get on with this?

I've gotten as far as https://github.com/openlgtv/buildroot-nc4/issues/12

**Comment by IngwiePhoenix** [comment]
Adding `-lrt` fixed some of the issues, yeah. It's been quite a while since I last looked into this... Sorry. I will look at what i ended up doing later and put it here. :)
