### ISSUE TITLE
Still referencing tmp/cirrus-ci-build/output/host?

### ISSUE THREAD

**Issue by craigcarnell** [openlgtv/buildroot-nc4#9]
I have downloaded and extracted to:

/home/developer/toolchain/arm-webos-linux-gnueabi_sdk-buildroot

I've then ran ./relocate-sdk.sh which said it was successful. I don't think running environment-setup is required.

I added to my ~/.profile to make it easier to find the binaries.
```
# toolchain
export SDK_PATH="/home/developer/toolchain/arm-webos-linux-gnueabi_sdk-buildroot"
if [ -d "$SDK_PATH=/bin" ]; then
  export "PATH=$SDK_PATH/bin:$SDK_PATH/sbin:$PATH"
fi
```

I've started a compilation, it succeeds until this point. It still seems to be referencing tmp/cirrus-ci-build/output/host/ ?

```
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /tmp/cirrus-ci-build/output/host/lib/perl5/site_perl/5.34.1/x86_64-linux /tmp/cirrus-ci-build/output/host/lib/perl5/site_perl/5.34.1 /tmp/cirrus-ci-build/output/host/lib/perl5/5.34.1/x86_64-linux /tmp/cirrus-ci-build/output/host/lib/perl5/5.34.1) at bin/autom4te line 26.
```

Also
```
checking whether /home/developer/toolchain/arm-webos-linux-gnueabi_sdk-buildroot/bin/perl Fcntl::flock is implemented... Can't locate Fcntl.pm in @INC (you may need to install the Fcntl module) (@INC contains: /tmp/cirrus-ci-build/output/host/lib/perl5/site_perl/5.34.1/x86_64-linux /tmp/cirrus-ci-build/output/host/lib/perl5/site_perl/5.34.1 /tmp/cirrus-ci-build/output/host/lib/perl5/5.34.1/x86_64-linux /tmp/cirrus-ci-build/output/host/lib/perl5/5.34.1) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

output of sudo find / -name strict.pm
```
/usr/lib/x86_64-linux-gnu/perl-base/strict.pm
/usr/share/perl/5.34.0/strict.pm
/snap/core20/1623/usr/lib/x86_64-linux-gnu/perl-base/strict.pm
/snap/core20/1778/usr/lib/x86_64-linux-gnu/perl-base/strict.pm
/home/developer/toolchain/arm-webos-linux-gnueabi_sdk-buildroot/lib/perl5/5.34.1/strict.pm
```

**Comment by smx-smx** [comment]
Remove bin/perl (and maybe bin/cmake) from the toolchain. The buildbot host (Cirrus CI) doesn't have perl and cmake installed, and so they are compiled as part of the build process.
However, we have noticed the prebuilt perl/cmake binary do cause issues on other hosts.
A workaround might be to remove them after building, or to install perl+cmake on the buildbot, but I'm hesitant for now

**Comment by craigcarnell** [comment]
@smx-smx perfect thanks. I've changed my PATH variable.

**Comment by smx-smx** [comment]
Another thing to remember is that you should run `./relocate-sdk.sh` in the toolchain directory once you extract it. This buildroot-provided script will translate leftover paths according to the directory you extracted it into
